### ISSUE TITLE
text-anchor attribute doesn't work

### ISSUE THREAD

**Issue by jonestheguitar** [hervegirod/fxsvgimage#19]
This SVG:
![textAnchor](https://user-images.githubusercontent.com/16610817/170777186-f1867092-7fc5-40f3-b2ae-d56b5f9588ea.svg)

Gets rendered by fxsvgimage like this:
![text-anchor](https://user-images.githubusercontent.com/16610817/170777540-d756c8ba-0f46-4bac-bb85-f973125b5c58.png)

The text-anchor attribute seems to be ignored - the text is always anchored to "start".

**Comment by hervegirod** [comment]
Fixed in master
