### ISSUE TITLE
Units not all handled correctly

### ISSUE THREAD

**Issue by jonestheguitar** [hervegirod/fxsvgimage#22]
This SVG:
![units](https://user-images.githubusercontent.com/16610817/170780574-aa099d3e-b778-4ae9-beef-68225841f040.svg)

gets rendered by fxsvgimage as a single large green circle.

Some analysis of what's happening shows that the circles with units cm, em, ex, mm and in aren't rendered at all.
The no-unit and px unit circles render ok but are obscured by an overly large pt unit circle.

**Comment by hervegirod** [comment]
I should be fixed on master
