### ISSUE TITLE
<line> x1, y1, x2, y2 attributes don't default to zero if omitted

### ISSUE THREAD

**Issue by jonestheguitar** [hervegirod/fxsvgimage#23]
In this SVG:
![line](https://user-images.githubusercontent.com/16610817/170836165-dc555ec5-eeda-4690-ba02-bc3e82e93f5c.svg)

fxsvgimage doesn't render the line - it works if I add x1="0" y1="0" attributes but if omitted those should default to zero (likewise for x2 and y2).

**Comment by hervegirod** [comment]
Fixed in master
