### ISSUE TITLE
<polygon> element not rendering

### ISSUE THREAD

**Issue by jonestheguitar** [hervegirod/fxsvgimage#24]
This SVG:
![polygon](https://user-images.githubusercontent.com/16610817/170836504-30f5778d-bd72-4ccf-9841-2cb657f8fe03.svg)

Doesn't display when rendered by fxsvgimage.

**Comment by jonestheguitar** [comment]
Doesn't display as a polyline either - something about the point sequence maybe?

**Comment by hervegirod** [comment]
Fixed in master

**Comment by hervegirod** [comment]
The tokenizer was not working correctly in this case. I simplified it, and now it works!
