### ISSUE TITLE
Scaling does not work

### ISSUE THREAD

**Issue by xeruf** [hervegirod/fxsvgimage#25]
When I load an SVGImage and call scaleTo on it, it does not change its size :/
Using LoaderParameters does work, however!

**Comment by hervegirod** [comment]
Hello,

It works in the use cases I tried. Did you get the result of the scaleTo method, or did you continue to use the initial SVGImage ? The first image is not changed, the result creates a new one.

**Comment by hervegirod** [comment]
I think that it would be better to scale the initial image however, rather than creating a new one. What do you think?

**Comment by hervegirod** [comment]
Now by default scaling an SVGImage scale the initial SVGImage rather than creating another one. Fixed in master

**Comment by xeruf** [comment]
ah yes, thanks :)
