### ISSUE TITLE
Polygons not rendered

### ISSUE THREAD

**Issue by dandan2611** [hervegirod/fxsvgimage#32]
Hello,
It seems that <polygons> in SVGs cannot be rendered properly (returns null SVGImage).
I am able to render a <path> SVG properly.
First SVG with path

![fi-rs-a](https://user-images.githubusercontent.com/19997696/175520320-f5f5dd4a-16b2-47f4-b186-e0f12beaa516.svg)
Second SVG with polygon

![fi-ss-plus](https://user-images.githubusercontent.com/19997696/175520392-53854c21-8fa1-4aff-a3b5-042d01819334.svg)

I actually have no errors in my console.
Thanks :)

**Comment by boessu** [comment]
+1 here. SVG's created from [PlantUML](https://github.com/plantuml/plantuml) do missing polygons too. PlantUML does create fairly trivial but very useful SVG's and have more a "reporting" character. Attached two example files for testing, as I would say displaying such diagrams as nodes in JavaFX is more or less one of the main target use cases of this library here. ;-)

![class_diagram](https://user-images.githubusercontent.com/2807976/211653393-82605ae9-6e19-4664-8048-6c354f0e8869.svg)
![sequenzdiagramm](https://user-images.githubusercontent.com/2807976/211654711-3ac398bd-c365-4631-9a2a-839dcd9e8528.svg)

**Comment by hervegirod** [comment]
Should be fixed as of next 1.1 version. Will upload this version this evening normally.
