### ISSUE TITLE
Can I use an SVG XML string directly?

### ISSUE THREAD

**Issue by kxygk** [hervegirod/fxsvgimage#35]
I'm programmatically generating SVG maps (using a separate library of mine). I can then serialize those into string of the SVG XML. I can then of course write those to disk, but is there some way I could feed the string directly into `[fxsvgimage](https://github.com/hervegirod/fxsvgimage)` to get back an SVG Group to display? (ie. bypass needing to make a temp file).

Btw, is there a Javadoc of the library hosted somewhere? I'm only seeing the Sourceforge guide - which is handy but I don't think it's comprehensive. I'm really sorry if I somehow missed what I was looking for here :S

**Comment by hervegirod** [comment]
Hello, the javadoc is provided as a zip alongside the wiki content, in the 
`fxsvgImage-docs-<version>.zip` (`fxsvgImage-docs-1.1.zip` for example in the last version).

You can load a string contet directly using the `SVGLoader.load(String content)`.

**Comment by kxygk** [comment]
Oh that's great! Thank you. I somehow missed that. And thank you for the prompt reply
